### ISSUE TITLE
Error job 4

### ISSUE THREAD

**Issue by mstoffel-sag** [SoftwareAG/sagdevops-cc-docker-builder#4]
Just copied the lic to the dir and tried the build.  Got the following errors:

017/11/07 09:31:38 ERROR #8     [SPMJOBE0003] Job -2 failed!
java.lang.RuntimeException: Error occurred while creating a template on the remote  managed node with alias: local. Remote task status is [SPMTEME0019] Error occurred during execution of operation APPLY on template container_msc-server_local >> [SPMPROE0028] Artifact with id "MSC" and version "null" not found in the repositories REPOSITORY-sdc.softwareag.com-dataservewebM100-repository
	at com.softwareag.platform.management.client.template.impl.BaseTemplateJobCallable.reportError(BaseTemplateJobCallable.java:55)
	at com.softwareag.platform.management.client.template.impl.ApplyTemplateJobCallable.analyzeApplyTemplateJobStatus(ApplyTemplateJobCallable.java:147)
	at com.softwareag.platform.management.client.template.impl.ApplyTemplateJobCallable.call(ApplyTemplateJobCallable.java:95)
	at com.softwareag.platform.management.client.template.impl.ApplyTemplateJobCallable.retry(ApplyTemplateJobCallable.java:183)
	at com.softwareag.platform.management.client.template.impl.ApplyTemplateJobCallable.analyzeApplyTemplateJobStatus(ApplyTemplateJobCallable.java:138)
	at com.softwareag.platform.management.client.template.impl.ApplyTemplateJobCallable.call(ApplyTemplateJobCallable.java:95)
	at com.softwareag.platform.management.client.template.impl.ApplyTemplateJobCallable.call(ApplyTemplateJobCallable.java:38)
	at com.softwareag.platform.management.jobmanager.impl.JobCallableWrapper.call(JobCallableWrapper.java:27)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.softwareag.platform.management.jobmanager.impl.JobImpl.run(JobImpl.java:113)
	at com.softwareag.platform.management.jobmanager.impl.SynchronousJobManagerServiceImpl.startInternal(SynchronousJobManagerServiceImpl.java:52)
	at com.softwareag.platform.management.jobmanager.impl.SynchronousJobManagerServiceImpl.start(SynchronousJobManagerServiceImpl.java:36)
	at com.softwareag.platform.management.client.template.composite.impl.ApplyCompositeTemplateStripeJob.applySnapshotTemplate(ApplyCompositeTemplateStripeJob.java:269)
	at com.softwareag.platform.management.client.template.composite.impl.ApplyCompositeTemplateStripeJob.call(ApplyCompositeTemplateStripeJob.java:93)
	at com.softwareag.platform.management.client.template.composite.impl.ApplyCompositeTemplateStripeJob.call(ApplyCompositeTemplateStripeJob.java:40)
	at com.softwareag.platform.management.jobmanager.impl.JobCallableWrapper.call(JobCallableWrapper.java:27)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.softwareag.platform.management.jobmanager.impl.JobImpl.run(JobImpl.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017/11/07 09:31:38 INFO  #8     stripe template [msc-server] node [local] layer [runtime] end
2017/11/07 09:31:38 ERROR #8     [SPMJOBE0003] Job 4 failed!
com.softwareag.platform.management.common.exceptions.PlatformManagerException: Un-handled internal server error. Error occurred while creating a template on the remote  managed node with alias: local. Remote task status is [SPMTEME0019] Error occurred during execution of operation APPLY on template container_msc-server_local >> [SPMPROE0028] Artifact with id "MSC" and version "null" not found in the repositories REPOSITORY-sdc.softwareag.com-dataservewebM100-repository
	at com.softwareag.platform.management.jobmanager.impl.JobImpl.extractExecutionExceptionCause(JobImpl.java:218)
	at com.softwareag.platform.management.jobmanager.impl.JobImpl.waitForResult(JobImpl.java:193)
	at com.softwareag.platform.management.client.template.composite.impl.ApplyCompositeTemplateStripeJob.applySnapshotTemplate(ApplyCompositeTemplateStripeJob.java:269)
	at com.softwareag.platform.management.client.template.composite.impl.ApplyCompositeTemplateStripeJob.call(ApplyCompositeTemplateStripeJob.java:93)
	at com.softwareag.platform.management.client.template.composite.impl.ApplyCompositeTemplateStripeJob.call(ApplyCompositeTemplateStripeJob.java:40)
	at com.softwareag.platform.management.jobmanager.impl.JobCallableWrapper.call(JobCallableWrapper.java:27)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.softwareag.platform.management.jobmanager.impl.JobImpl.run(JobImpl.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error occurred while creating a template on the remote  managed node with alias: local. Remote task status is [SPMTEME0019] Error occurred during execution of operation APPLY on template container_msc-server_local >> [SPMPROE0028] Artifact with id "MSC" and version "null" not found in the repositories REPOSITORY-sdc.softwareag.com-dataservewebM100-repository
	at com.softwareag.platform.management.client.template.impl.BaseTemplateJobCallable.reportError(BaseTemplateJobCallable.java:55)
	at com.softwareag.platform.management.client.template.impl.ApplyTemplateJobCallable.analyzeApplyTemplateJobStatus(ApplyTemplateJobCallable.java:147)
	at com.softwareag.platform.management.client.template.impl.ApplyTemplateJobCallable.call(ApplyTemplateJobCallable.java:95)
	at com.softwareag.platform.management.client.template.impl.ApplyTemplateJobCallable.retry(ApplyTemplateJobCallable.java:183)
	at com.softwareag.platform.management.client.template.impl.ApplyTemplateJobCallable.analyzeApplyTemplateJobStatus(ApplyTemplateJobCallable.java:138)
	at com.softwareag.platform.management.client.template.impl.ApplyTemplateJobCallable.call(ApplyTemplateJobCallable.java:95)
	at com.softwareag.platform.management.client.template.impl.ApplyTemplateJobCallable.call(ApplyTemplateJobCallable.java:38)
	at com.softwareag.platform.management.jobmanager.impl.JobCallableWrapper.call(JobCallableWrapper.java:27)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.softwareag.platform.management.jobmanager.impl.JobImpl.run(JobImpl.java:113)
	at com.softwareag.platform.management.jobmanager.impl.SynchronousJobManagerServiceImpl.startInternal(SynchronousJobManagerServiceImpl.java:52)
	at com.softwareag.platform.management.jobmanager.impl.SynchronousJobManagerServiceImpl.start(SynchronousJobManagerServiceImpl.java:36)
	... 9 more
2017/11/07 09:31:38 ERROR #8     Job completed: id 4 status ERROR started Tue Nov 07 09:26:56 UTC 2017 - Apply of composite template container on local for runtime (msc-server)
2017/11/07 09:31:38 ERROR #8     job: 4 -> Un-handled internal server error. Error occurred while creating a template on the remote  managed node with alias: local. Remote task status is [SPMTEME0019] Error occurred during execution of operation APPLY on template container_msc-server_local >> [SPMPROE0028] Artifact with id "MSC" and version "null" not found in the repositories REPOSITORY-sdc.softwareag.com-dataservewebM100-repository

**Comment by sergeipogrebnyak** [comment]
The builder supports 10.1 only. You cannot build 10.1 containers

**Comment by sergeipogrebnyak** [comment]
Fixed

https://github.com/SoftwareAG/sagdevops-cc-docker-builder/commit/ee90e83dd068ab01f07a9b295ab7683dc6bec2f1
